# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image: DockerFile
# Command to start on workspace startup (optional)
tasks:
  - init: npm install
    command: ionic cordova run browser
# Ports to expose on workspace startup (optional)
ports:
  - port: 8000
    onOpen: open-preview
